Unify app interface
WilhelmusLab/ebseg pull request #46
Opened 2024-08-07 13:21 UTC by hollandjg

2024-08-13 18:21 UTC, cpaniaguam commented on flow.cylc
> +            ${FSDPROC} load $IMGDIR/tci.tiff --kind truecolor --datetime ${DATE} --bbox $BBOX
Using the variables looks so much cleaner, thanks!

2024-08-13 18:49 UTC, cpaniaguam commented on src/ebfloeseg/app.py
Consider adding docstrings to these command functions or some comments clarifying what's going on.

2024-08-13 20:11 UTC, hollandjg commented on flow.cylc
>              BBOX=$($PYTHON -c "import pandas; print(','.join(str(s) for s in list(pandas.read_csv('${CYLC_WORKFLOW_RUN_DIR}/locations.csv', index_col='location').loc['${LOCATION}'][['left_x', 'lower_
That'll be in #45 ! No problem.

2024-08-13 20:37 UTC, hollandjg commented on src/ebfloeseg/app.py
Makes a lot of sense. I've updated the command help texts and added the citation to the top of the app.

2024-08-14 13:48 UTC, cpaniaguam requested changes
One observation and one old typo fix here.

2024-08-14 13:48 UTC, cpaniaguam commented on src/ebfloeseg/app.py
> +):
Use the sample data set here?

2024-08-14 13:48 UTC, cpaniaguam commented on src/ebfloeseg/app.py
> +    epilog=f"Example: {name} --data-direc /path/to/data --save_figs --save-direc /path/to/save --land /path/to/landfile",
```suggestion
    epilog=f"Example: {name} --data-direc /path/to/data --save-figs --save-direc /path/to/save --land /path/to/landfile",
```

2024-08-14 15:47 UTC, hollandjg commented on src/ebfloeseg/app.py
> +):
That's in #52

2024-08-14 15:53 UTC, cpaniaguam approved these changes

2024-08-14 17:00 UTC, merged